# Generated by Django 4.1.5 on 2023-01-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_cover_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_cover',
            field=models.TextField(blank=True),
        ),
    ]
