# Generated by Django 4.1.5 on 2023-01-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_google_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_description',
            field=models.TextField(blank=True),
        ),
    ]
